#! /bin/sh

xss-lock --transfer-sleep-lock -- i3lock-fancy --nofork &
nitrogen --restore&
picom --config /home/srinath/.config/picom/picom.conf &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
greenclip daemon &
rofi -modi drun -show drun -line-padding 4 \
                -columns 2 -padding 50 -hide-scrollbar \
                -show-icons &
/home/srinath/.config/polybar/launch.sh &                                             
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a Google-chrome desktop='^2'
bspc rule -a Vivaldi-stable desktop='^2'
bspc rule -a Brave-browser desktop='^2'
bspc rule -a zoom desktop='^4'
bspc rule -a whatsapp-nativefier-d40211 desktop='^4'
bspc rule -a Signal desktop='^4'
bspc rule -a Spotify desktop='^6'
bspc rule -a Thunar desktop='^3'
bspc rule -a Geany desktop='^5'
bspc rule -a code-oss desktop='^5'
bspc rule -a Minetest desktop='^7'
bspc rule -a "VirtualBox Manager" desktop='^8'
bspc rule -a Pavucontrol state=floating

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#6272a4"
bspc config presel_feedback_color "#6272a4"

